import test from 'ava';
import { listComponentsTool } from './list_components.js';

const handler = listComponentsTool.handler;

function getText(response: ReturnType<typeof handler>): string {
  return response.content[0].text;
}

test('handler: output contains React component names from generated descriptions.json', (t) => {
  const result = getText(handler({}));
  // AnalyticalTable comes from DESCRIPTIONS.components (gitignored, generated by extract:descriptions)
  // If the extraction pipeline breaks, this fails
  t.true(result.includes('**AnalyticalTable**'));
});

test('handler: Web Components (Wrapped) category lists components with total count', (t) => {
  const result = getText(handler({ category: 'Web Components (Wrapped)' }));
  t.true(result.includes('Web Components (Wrapped)'));
  // Total count comes from Object.keys(DESCRIPTIONS.webComponents) — generated data
  const totalMatch = result.match(/\*\*Total\*\*: (\d+)/);
  t.truthy(totalMatch, 'should include a total count');
  t.true(Number(totalMatch![1]) > 50, 'should have a meaningful number of web components');
});
