import test from 'ava';
import { listComponentsTool } from './list_components.js';

const handler = listComponentsTool.handler;

function getText(response: ReturnType<typeof handler>): string {
  return response.content[0].text;
}

test('handler: output contains React component names from generated descriptions.json', (t) => {
  const result = getText(handler({}));
  // AnalyticalTable comes from DESCRIPTIONS.components (gitignored, generated by extract:descriptions)
  // If the extraction pipeline breaks, this fails
  t.true(result.includes('**AnalyticalTable**'));
});

test('handler: Web Components (Wrapped) category lists components with total count', (t) => {
  const result = getText(handler({ category: 'Web Components (Wrapped)' }));
  t.true(result.includes('Web Components (Wrapped)'));
  // Total count comes from Object.keys(DESCRIPTIONS.webComponents) — generated data
  const totalMatch = result.match(/\*\*Total\*\*: (\d+)/);
  t.truthy(totalMatch, 'should include a total count');
  t.true(Number(totalMatch![1]) > 50, 'should have a meaningful number of web components');
  // Must not include React-only components
  t.false(result.includes('_(React)_'), 'should not include React components when filtering for Web Components');
});

test('handler: unfiltered output does not include Web Components (Wrapped) catch-all', (t) => {
  const result = getText(handler({}));
  t.false(result.includes('### Web Components (Wrapped)'), 'catch-all section should not appear without filter');
  // But categorized web components should still appear
  t.true(result.includes('_(Web Component)_'), 'web components should appear in their categorized sections');
});

test('handler: category filter shows only that category', (t) => {
  const result = getText(handler({ category: 'Charts' }));
  t.true(result.includes('Charts'));
  t.false(result.includes('### Inputs'));
  t.false(result.includes('### Data Display'));
});
