import test from 'ava';
import { createAppTool } from './create_app.js';

const handler = createAppTool.handler;

function getText(response: ReturnType<typeof handler>): string {
  return response.content[0].text;
}

test('handler: valid template returns degit instructions from generated project-templates.json', (t) => {
  // docs/project-templates.json is gitignored (generated by bundle:docs)
  // If the path or generation breaks, templates will be empty and this fails
  const result = getText(handler({ template: 'vite-ts', appName: 'my-app' }));
  t.true(result.includes('degit'));
  t.true(result.includes('my-app'));
});
