import test, { type ExecutionContext } from 'ava';
import { z } from 'zod';
import { getComponentApiTool } from './get_component_api.js';

const handler = getComponentApiTool.handler;
const outputSchema = z.object(getComponentApiTool.outputSchema);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getStructured(response: ReturnType<typeof handler>): any {
  if (!('structuredContent' in response)) {
    throw new Error('Expected structuredContent in response');
  }
  return response.structuredContent;
}

function assertMatchesOutputSchema(t: ExecutionContext, data: unknown) {
  const result = outputSchema.safeParse(data);
  if (!result.success) {
    t.fail(
      `Output schema validation failed:\n${result.error.issues.map((i) => `  ${i.path.join('.')}: ${i.message}`).join('\n')}`,
    );
  }
}

test('handler: finds component case-insensitively from generated component-apis.json', (t) => {
  // component-apis.json is gitignored (generated by extract:descriptions)
  // Also verifies findComponent() toLowerCase logic
  const result = getStructured(handler({ componentName: 'button' }));
  t.truthy(result.props);
  t.falsy(result.error);
});

test('handler: AnalyticalTable is from @ui5/webcomponents-react', (t) => {
  // Verifies the "components" category (separate from webComponents tested above)
  const result = getStructured(handler({ componentName: 'AnalyticalTable' }));
  t.is(result.package, '@ui5/webcomponents-react');
});

test('handler: not-found returns error with available components list', (t) => {
  // Input is z.string() (not z.enum), so this path is reachable
  const result = getStructured(handler({ componentName: 'FakeWidget' }));
  t.is(result.errorType, 'not_found');
  t.true(result.availableComponents.length > 0);
});

test('handler: AnalyticalTable response passes outputSchema validation', (t) => {
  const result = getStructured(handler({ componentName: 'AnalyticalTable' }));
  assertMatchesOutputSchema(t, result);
  t.pass();
});

test('handler: not-found response passes outputSchema validation', (t) => {
  const result = getStructured(handler({ componentName: 'FakeWidget' }));
  assertMatchesOutputSchema(t, result);
  t.pass();
});
